# Generated by Django 2.2.8 on 2019-12-30 18:05

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('przychodnia_pacjent', '0001_initial'),
        ('przychodnia_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wizyta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(blank=True, null=True)),
                ('diagnoza', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REJ', 'Zarejestrowana'), ('ZAK', 'Zakończona'), ('ANUL', 'Anulowana')], default='REJ', max_length=4)),
                ('dt_rej', models.DateTimeField(auto_now_add=True)),
                ('dt_zak_anul', models.DateTimeField(blank=True, null=True)),
                ('lekarz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='przychodnia_app.Lekarz')),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='przychodnia_pacjent.Pacjent')),
                ('rejestratorka', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='przychodnia_app.Rejestratorka')),
            ],
            options={
                'verbose_name_plural': 'Wizyty',
                'ordering': ['dt_rej'],
            },
            managers=[
                ('wizyty', django.db.models.manager.Manager()),
            ],
        ),
    ]
