# Generated by Django 2.2.6 on 2019-11-04 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('przychodnia_app', '0001_initial'),
        ('przychodnia_pacjent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wizyta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField()),
                ('diagnoza', models.TextField()),
                ('status', models.CharField(choices=[('REJ', 'Zarejestrowana'), ('ZAK', 'Zakończona'), ('ANUL', 'Anulowana')], max_length=4)),
                ('dt_rej', models.DateTimeField(auto_now_add=True)),
                ('dt_zak_anul', models.DateTimeField(null=True)),
                ('lekarz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='przychodnia_app.Lekarz')),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='przychodnia_pacjent.Pacjent')),
                ('rejestratorka', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='przychodnia_app.Rejestratorka')),
            ],
        ),
    ]
