# Generated by Django 2.2.6 on 2020-01-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('przychodnia_wizyta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizyta',
            name='dt_rej_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
