# Generated by Django 2.1 on 2019-12-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('przychodnia_wizyta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizyta',
            name='opis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
