# Generated by Django 2.2.6 on 2019-11-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('przychodnia_wizyta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wizyta',
            options={'verbose_name_plural': 'Wizyty'},
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='status',
            field=models.CharField(choices=[('REJ', 'Zarejestrowana'), ('ZAK', 'Zakończona'), ('ANUL', 'Anulowana')], default='REJ', max_length=4),
        ),
    ]
