# Generated by Django 2.1 on 2019-12-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('przychodnia_wizyta', '0002_auto_20191214_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizyta',
            name='diagnoza',
            field=models.TextField(blank=True, null=True),
        ),
    ]
