# Generated by Django 2.2 on 2019-12-06 13:22

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('przychodnia_wizyta', '0002_auto_20191104_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wizyta',
            options={'ordering': ['-dt_rej'], 'verbose_name_plural': 'Wizyty'},
        ),
        migrations.AlterModelManagers(
            name='wizyta',
            managers=[
                ('wizyty', django.db.models.manager.Manager()),
            ],
        ),
    ]
