# Generated by Django 2.1 on 2019-12-28 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('przychodnia_wizyta', '0003_auto_20191217_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wizyta',
            options={'ordering': ['dt_rej'], 'verbose_name_plural': 'Wizyty'},
        ),
    ]
