# Generated by Django 2.2.6 on 2019-11-01 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rejestratorka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='REJESTRATORKA', max_length=16)),
                ('imie', models.CharField(max_length=32, verbose_name='Imie')),
                ('nazwisko', models.CharField(max_length=32, verbose_name='Nazwisko')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lekarz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='LEKARZ', max_length=16)),
                ('imie', models.CharField(max_length=32, verbose_name='Imie')),
                ('nazwisko', models.CharField(max_length=32, verbose_name='Nazwisko')),
                ('npwz', models.CharField(max_length=7, unique=True, verbose_name='NPWZ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
