# Generated by Django 2.2.6 on 2019-11-01 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('przychodnia_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lekarz',
            options={'verbose_name_plural': 'Lekarze'},
        ),
        migrations.AlterModelOptions(
            name='rejestratorka',
            options={'verbose_name_plural': 'Rejestratorki'},
        ),
        migrations.AlterField(
            model_name='lekarz',
            name='role',
            field=models.CharField(default='LEKARZ', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='lekarz',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rejestratorka',
            name='role',
            field=models.CharField(default='REJESTRATORKA', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='rejestratorka',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
