# Generated by Django 2.1 on 2019-12-28 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_slownikbadan'),
        ('przychodnia_app', '0002_auto_20191217_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadanieFizykalne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wynik', models.BooleanField(default=False)),
                ('slownik', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.SlownikBadan')),
            ],
            options={
                'verbose_name_plural': 'Badania Fizykalne',
            },
        ),
    ]
