# Generated by Django 2.1 on 2019-12-29 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('przychodnia_app', '0003_badaniefizykalne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badaniefizykalne',
            name='slownik',
        ),
        migrations.DeleteModel(
            name='BadanieFizykalne',
        ),
    ]
