# Generated by Django 2.2.6 on 2019-11-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('REJ', 'REJESTRATORKA'), ('LEK', 'LEKARZ')], max_length=16, null=True),
        ),
    ]
