# Generated by Django 2.1 on 2019-12-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlownikBadan',
            fields=[
                ('key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('typ', models.CharField(choices=[('L', 'Laboratoryjne'), ('F', 'Fizykalne')], max_length=1)),
                ('nazwa', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Słownik Badań',
            },
        ),
    ]
