# Generated by Django 2.2.6 on 2019-11-09 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('przychodnia_pacjent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacjent',
            name='adres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='przychodnia_pacjent.Adres'),
        ),
    ]
