# Generated by Django 2.1 on 2019-12-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorium_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kierowniklabarotorium',
            name='imie',
            field=models.CharField(max_length=32, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='laborant',
            name='imie',
            field=models.CharField(max_length=32, verbose_name='Imię'),
        ),
    ]
