# Generated by Django 2.2.8 on 2019-12-30 18:05

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('przychodnia_wizyta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadanieFizykalne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wynik', models.TextField()),
                ('slownik', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.SlownikBadan')),
                ('wizyta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='przychodnia_wizyta.Wizyta')),
            ],
            options={
                'verbose_name_plural': 'Badania Fizykalne',
            },
            managers=[
                ('badania', django.db.models.manager.Manager()),
            ],
        ),
    ]
