# Generated by Django 2.1 on 2019-12-29 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('przychodnia_wizyta', '0004_auto_20191228_1420'),
        ('common', '0002_slownikbadan'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadanieFizykalne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wynik', models.BooleanField(default=False)),
                ('slownik', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.SlownikBadan')),
                ('wizyta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='przychodnia_wizyta.Wizyta')),
            ],
            options={
                'verbose_name_plural': 'Badania Fizykalne',
            },
        ),
    ]
